; PlatformIO Project Configuration File
[platformio]
src_dir = toilet_kat_change
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = toilet_kat_change/partitions.csv
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.sdkconfig = toilet_kat_change/sdkconfig.defaults

lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library
    pololu/DualMAX14870MotorShield
    br3ttb/PID
    https://github.com/drf5n/Arduino-PID-Library.git
